project:
  type: website

website:
  title: "Global Cheese Analysis Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        text: "GitHub"
        href: https://github.com/ETC5523-2024/assignment-3-creating-a-blog-shuwang0405.git

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2



